### ISSUE TITLE
Add new region`s code

### ISSUE THREAD

**Issue by Belobokovm** [avto-dev/static-references-data#15]
### Is your feature request related to a problem?
> need new region code to pass verification

### Describe the solution you'd like
> add a new region code to pass verification

### Additional context
> Add 702 code

```
{
        "title": "Республика Башкортостан",
        "short": [
            "Башкортостан",
            "Башкирия"
        ],
        "code": 2,
        "gibdd": [
            2,
            102,
            702
        ],
        "okato": "80",
        "code_iso_31662": "RU-BA",
        "type": "Республика"
    }
```

**Comment by Reallife** [comment]
Resolved in [#16]

[#16]:https://github.com/avto-dev/static-references-data/pull/16
