### ISSUE TITLE
Нужно добавить справочник типов транспортных средств

### ISSUE THREAD

**Issue by Reallife** [avto-dev/static-references-data#8]
### Is your feature request related to a problem?

Возникла необходимость в справочнике типов транспортных средств.

### Describe the solution you'd like

Был найден "Кодификатор типов транспортных средств", утверждённый [Приказом МВД РФ от 31.03.1995 N 125 (ред. от 29.07.1997) "Об учете автомототранспортных средств и специальной продукции Госавтоинспекции"][vehicle_types_source]. Предлагается на основе этого кодификатора составить справочник типов транспортных средств. 

## Additional context

Указанный выше [приказ][vehicle_types_source] утратил свою силу с выходом [Приказа МВД России от 03.12.2007 N 1144 (ред. от 27.01.2014) "О системе информационного обеспечения подразделений Госавтоинспекции"][vehicle_types_source_canceling], но некоторые источники данных до сих пор поставляют информацию с учётом данного кодификатора. Поэтому необходимость в ведении такого справочника остаётся актуальной.

[vehicle_types_source]:http://www.consultant.ru/cons/cgi/online.cgi?req=doc&n=313930&base=EXP&from=313930-1669-diff&rnd=14B238716852CBC1B21D464E9F3969CA#005305945620298047
[vehicle_types_source_canceling]:http://www.consultant.ru/cons/cgi/online.cgi?from=80265-37&rnd=14B238716852CBC1B21D464E9F3969CA&req=doc&base=LAW&n=164386&REFDOC=80265&REFBASE=LAW#8apdsut6en

**Comment by tarampampam** [comment]
Released: https://github.com/avto-dev/static-references-data/releases/tag/v2.8.0
